name: Run Tests

on: 
  push:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
          sudo apt update
          sudo apt install -y cmake python3-pytest
          cd ./tests
          python3 -m pytest -sv
